### ISSUE TITLE
MMM-sort wont load help needed 

### ISSUE THREAD

**Issue by gauka12345** [mykle1/MMM-SORT#2]
Hi every one.. 

i have got an issue with MMM-SORT - the module wont load, 

is stuck on ( first the tide rushes in.. ) 

does anyone know why  this is happened. i have  valid key and also bough a credits so it should work correctly.

**Comment by mykle1** [comment]
Then you must be getting an error somewhere. The module works as expected. I just tested it. If you need help go to the magicmirror forum and start a topic asking for help. I will help you there
